#pragma warning disable AA0005, AA0008, AA0018, AA0021, AA0072, AA0137, AA0201, AA0206, AA0218, AA0228, AL0254, AL0424, AS0011, AW0006 // ForNAV settings
TableExtension 50012 "tableextension50012" extends "Sales Header" 
{
    fields
    {

        //Unsupported feature: Code Modification on ""Posting Date"(Field 20).OnValidate".

        //trigger OnValidate()
        //Parameters and return type have not been exported.
        //>>>> ORIGINAL CODE:
        //begin
            /*
            TESTFIELD("Posting Date");
            TestNoSeriesDate(
              "Posting No.","Posting No. Series",
            #4..26
              IF DeferralHeadersExist THEN
                ConfirmUpdateDeferralDate;
            SynchronizeAsmHeader;
            */
        //end;
        //>>>> MODIFIED CODE:
        //begin
            /*

            #1..29
            */
        //end;
        field(50020;"Shortcut Dimension 3 Code";Code[20])
        {
            CaptionClass = '1,1,3';
            Caption = 'Shorstcut Dimension 3 Code';
            TableRelation = "Dimension Value".Code where ("Global Dimension No."=const(3));

            trigger OnValidate()
            begin
                //ValidateShortcutDimCode(3,"Shortcut Dimension 3 Code");
            end;
        }
        field(50021;"Shortcut Dimension 4 Code";Code[20])
        {
            CaptionClass = '1,1,4';
            Caption = 'Shortcut Dimension 4 Code';
            TableRelation = "Dimension Value".Code where ("Global Dimension No."=const(4));

            trigger OnValidate()
            begin
                //ValidateShortcutDimCode(4,"Shortcut Dimension 4 Code");
            end;
        }
        field(50022;"Shortcut Dimension 5 Code";Code[20])
        {
            CaptionClass = '1,1,5';
            Caption = 'Shortcut Dimension 5 Code';
            TableRelation = "Dimension Value".Code where ("Global Dimension No."=const(5));

            trigger OnValidate()
            begin
                //ValidateShortcutDimCode(5,"Shortcut Dimension 5 Code");
            end;
        }
        field(50023;Cancelled;Boolean)
        {
        }
        field(50024;"Cancelled By";Code[20])
        {
        }
        field(50025;"Cancelled Date";Date)
        {
        }
        field(50026;"Created By";Code[20])
        {
        }
        field(50027;"Created Date Time";DateTime)
        {
        }
        field(50028;Type;Option)
        {
            OptionCaption = 'Normal,Authentication Device';
            OptionMembers = Normal,"Authentication Device";
        }
        // field(85000;"Registration No.";Code[30])
        // {
        //     DataClassification = ToBeClassified;
        //     TableRelation = "Examination Account";
        // }
    }


    //Unsupported feature: Code Modification on "OnDelete".

    //trigger OnDelete()
    //>>>> ORIGINAL CODE:
    //begin
        /*
        IF NOT UserSetupMgt.CheckRespCenter(0,"Responsibility Center") THEN
          ERROR(
            Text022,
        #4..44

        IF IdentityManagement.IsInvAppId AND CustInvoiceDisc.GET(SalesHeader."Invoice Disc. Code") THEN
          CustInvoiceDisc.DELETE; // Cleanup of autogenerated cust. invoice discounts
        */
    //end;
    //>>>> MODIFIED CODE:
    //begin
        /*
        #1..47

        */
    //end;
}

